// login
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// user data
export const REQUEST_USER_DATA_SUCCESS = "REQUEST_USER_DATA_SUCCESS";
export const REQUEST_USER_DATA_FAIL = "REQUEST_USER_DATA_FAIL";

// user playlists, albums
export const FETCH_PLAYLISTS_SUCCESS = "FETCH_PLAYLISTS_SUCCESS";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";

// export const FOLLOW_PLAYLISTS_SUCCESS = "FOLLOW_PLAYLISTS_SUCCESS";
// export const FOLLOW_PLAYLISTS_FAIL = "FOLLOW_PLAYLISTS_FAIL";
// export const UNFOLLOW_PLAYLISTS_SUCCESS = "UNFOLLOW_PLAYLISTS_SUCCESS";
// export const UNFOLLOW_PLAYLISTS_FAIL = "UNFOLLOW_PLAYLISTS_FAIL";

//player
export const PLAY = "PLAY";
export const INIT_PLAYER = "INIT_PLAYER";
export const SET_PLAYER_STATUS = "SET_PLAYER_STATUS";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const PAUSED = "PAUSED";
