export const NAV_MENU = [
   { title: "Cá nhân", icon: "ic-library", link: "/my-music", exact: false },
   { title: "Trang chủ", icon: "ic-mn-home", link: "/", exact: true },
   {
      title: "Thể loại",
      icon: "ic-mn-catalogue",
      link: "/categories",
      exact: false,
   },
   {
      title: "Nhạc mới",
      icon: "ic-mn-song",
      link: "/new-releases",
      exact: false,
   },
   {
      title: "Bài hát đã thích",
      icon: "ic-mn-top100",
      link: "/favorite-songs",
      exact: false,
   },
];

export const NAV_PLAYLIST = [
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
];
