export const NAV_MENU = [
   { title: "Cá nhân", icon: "ic-library", link: "/my-music" },
   { title: "Trang chủ", icon: "ic-mn-home", link: "/" },
   { title: "Thể loại", icon: "ic-mn-catalogue", link: "/categories" },
   { title: "Nhạc mới", icon: "ic-mn-song", link: "/new-releases" },
   { title: "Bài hát đã thích", icon: "ic-mn-top100", link: "/favorite-songs" },
];

export const NAV_PLAYLIST = [
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
   { title: "playlist1", link: "#" },
   { title: "playlist2", link: "#" },
   { title: "playlist3", link: "#" },
   { title: "playlist4", link: "#" },
];
